/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DocumentReview { 
    documentId?: number;
    favourite?: boolean;
    id?: number;
    like?: boolean;
    starVote?: number;
    studentCode?: string;
}
