/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface DocumentResult {
    copyrightWarning?: boolean;
    dateCreated?: Date;
    dateUpdated?: Date;
    departmentId?: number;
    departmentName?: string;
    description?: string;
    documentName?: string;
    keyword?: string;
    topicType?: number;
    documentType?: number;
    downloadsCount?: number;
    firstName?: string;
    id?: number;
    lastName?: string;
    lecturerCode?: string;
    status?: number;
    subjectId?: number;
    subjectName?: string;
    title?: string;
    userCreated?: string;
    userUpdated?: string;
    viewsCount?: number;
}
