/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Notification {
    content?: string;
    dateCreated?: string;
    id?: number;
    link?: string;
    status?: number;
    type?: number;
    username?: string;
}
