/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface StudentResult { 
    address?: string;
    birthday?: Date;
    classCode?: string;
    email?: string;
    firstName?: string;
    gender?: number;
    lastName?: string;
    password?: string;
    phoneNumber?: string;
    role?: number;
    studentCode?: string;
}
