/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { DocumentReview } from '../model/documentReview';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class DocumentReviewControllerService {

    protected basePath = 'http://localhost:9999';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createDocumentReview
     *
     * @param documentReview documentReview
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createDocumentReviewUsingPOST(documentReview: DocumentReview, observe?: 'body', reportProgress?: boolean): Observable<DocumentReview>;
    public createDocumentReviewUsingPOST(documentReview: DocumentReview, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DocumentReview>>;
    public createDocumentReviewUsingPOST(documentReview: DocumentReview, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DocumentReview>>;
    public createDocumentReviewUsingPOST(documentReview: DocumentReview, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (documentReview === null || documentReview === undefined) {
            throw new Error('Required parameter documentReview was null or undefined when calling createDocumentReviewUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<DocumentReview>(`${this.basePath}/api/document-review/create`,
            documentReview,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteDocumentReview
     *
     * @param ids ids
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteDocumentReviewUsingPOST(ids: Array<number>, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public deleteDocumentReviewUsingPOST(ids: Array<number>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public deleteDocumentReviewUsingPOST(ids: Array<number>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public deleteDocumentReviewUsingPOST(ids: Array<number>, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (ids === null || ids === undefined) {
            throw new Error('Required parameter ids was null or undefined when calling deleteDocumentReviewUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<boolean>(`${this.basePath}/api/document-review/delete`,
            ids,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getDocumentReview
     *
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDocumentReviewUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<DocumentReview>;
    public getDocumentReviewUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DocumentReview>>;
    public getDocumentReviewUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DocumentReview>>;
    public getDocumentReviewUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getDocumentReviewUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<DocumentReview>(`${this.basePath}/api/document-review/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getDocumentReviewsList
     *
     * @param propertySearch propertySearch
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDocumentReviewsListUsingPOST(propertySearch: any, observe?: 'body', reportProgress?: boolean): Observable<Array<DocumentReview>>;
    public getDocumentReviewsListUsingPOST(propertySearch: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DocumentReview>>>;
    public getDocumentReviewsListUsingPOST(propertySearch: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DocumentReview>>>;
    public getDocumentReviewsListUsingPOST(propertySearch: any, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (propertySearch === null || propertySearch === undefined) {
            throw new Error('Required parameter propertySearch was null or undefined when calling getDocumentReviewsListUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<DocumentReview>>(`${this.basePath}/api/document-review`,
            propertySearch,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateDocumentReview
     *
     * @param documentReview documentReview
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateDocumentReviewUsingPUT(documentReview: DocumentReview, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public updateDocumentReviewUsingPUT(documentReview: DocumentReview, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public updateDocumentReviewUsingPUT(documentReview: DocumentReview, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public updateDocumentReviewUsingPUT(documentReview: DocumentReview, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (documentReview === null || documentReview === undefined) {
            throw new Error('Required parameter documentReview was null or undefined when calling updateDocumentReviewUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<boolean>(`${this.basePath}/api/document-review/update`,
            documentReview,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
