/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {
    HttpClient, HttpHeaders, HttpParams,
    HttpResponse, HttpEvent
} from '@angular/common/http';
import {CustomHttpUrlEncodingCodec} from '../encoder';

import {Observable} from 'rxjs/Observable';

import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';
import {LecturerSubjectResult} from "../model/lecturerSubjectResult";


@Injectable()
export class LecturerSubjectControllerService {

    protected basePath = 'http://localhost:9999';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * getLecturerSubjectsList
     *
     * @param propertySearch propertySearch
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getLecturerSubjectsListUsingPOST(propertySearch: any, observe?: 'body', reportProgress?: boolean): Observable<Array<LecturerSubjectResult>>;
    public getLecturerSubjectsListUsingPOST(propertySearch: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<LecturerSubjectResult>>>;
    public getLecturerSubjectsListUsingPOST(propertySearch: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<LecturerSubjectResult>>>;
    public getLecturerSubjectsListUsingPOST(propertySearch: any, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (propertySearch === null || propertySearch === undefined) {
            throw new Error('Required parameter propertySearch was null or undefined when calling getLecturerSubjectsListUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Array<LecturerSubjectResult>>(`${this.basePath}/api/lecturer-subject`,
            propertySearch,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateLecturerSubject
     *
     * @param subjectId subjectId
     * @param lecturerCodes lecturerCodes
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateLecturerSubjectUsingPOST(subjectId: number, lecturerCodes: Array<string>, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public updateLecturerSubjectUsingPOST(subjectId: number, lecturerCodes: Array<string>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public updateLecturerSubjectUsingPOST(subjectId: number, lecturerCodes: Array<string>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public updateLecturerSubjectUsingPOST(subjectId: number, lecturerCodes: Array<string>, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (subjectId === null || subjectId === undefined) {
            throw new Error('Required parameter subjectId was null or undefined when calling updateLecturerSubjectUsingPOST.');
        }

        if (lecturerCodes === null || lecturerCodes === undefined) {
            throw new Error('Required parameter lecturerCodes was null or undefined when calling updateLecturerSubjectUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<boolean>(`${this.basePath}/api/lecturer-subject/update/${encodeURIComponent(String(subjectId))}`,
            lecturerCodes,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }
}
