/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import {Inject, Injectable, Optional} from '@angular/core';
import {
    HttpClient, HttpHeaders, HttpParams,
    HttpResponse, HttpEvent
} from '@angular/common/http';
import {CustomHttpUrlEncodingCodec} from '../encoder';

import {Observable} from 'rxjs/Observable';

import {SearchResultSubjectResult} from '../model/searchResultSubjectResult';
import {Subject} from '../model/subject';
import {SubjectResult} from '../model/subjectResult';

import {BASE_PATH, COLLECTION_FORMATS} from '../variables';
import {Configuration} from '../configuration';


@Injectable()
export class SubjectControllerService {

    protected basePath = 'http://localhost:9999';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional() @Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * createSubject
     *
     * @param subject subject
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createSubjectUsingPOST(subject: SubjectResult, observe?: 'body', reportProgress?: boolean): Observable<Subject>;
    public createSubjectUsingPOST(subject: SubjectResult, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Subject>>;
    public createSubjectUsingPOST(subject: SubjectResult, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Subject>>;
    public createSubjectUsingPOST(subject: SubjectResult, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (subject === null || subject === undefined) {
            throw new Error('Required parameter subject was null or undefined when calling createSubjectUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Subject>(`${this.basePath}/api/subject/create`,
            subject,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * deleteSubject
     *
     * @param ids ids
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteSubjectUsingPOST(ids: Array<number>, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public deleteSubjectUsingPOST(ids: Array<number>, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public deleteSubjectUsingPOST(ids: Array<number>, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public deleteSubjectUsingPOST(ids: Array<number>, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (ids === null || ids === undefined) {
            throw new Error('Required parameter ids was null or undefined when calling deleteSubjectUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<boolean>(`${this.basePath}/api/subject/delete`,
            ids,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getSubject
     *
     * @param id id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSubjectUsingGET(id: number, observe?: 'body', reportProgress?: boolean): Observable<SubjectResult>;
    public getSubjectUsingGET(id: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SubjectResult>>;
    public getSubjectUsingGET(id: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SubjectResult>>;
    public getSubjectUsingGET(id: number, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getSubjectUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [];

        return this.httpClient.get<SubjectResult>(`${this.basePath}/api/subject/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getSubjectsList
     *
     * @param propertySearch propertySearch
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSubjectsListUsingPOST(propertySearch?: any, observe?: 'body', reportProgress?: boolean): Observable<SearchResultSubjectResult>;
    public getSubjectsListUsingPOST(propertySearch?: any, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SearchResultSubjectResult>>;
    public getSubjectsListUsingPOST(propertySearch?: any, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SearchResultSubjectResult>>;
    public getSubjectsListUsingPOST(propertySearch?: any, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (propertySearch === null || propertySearch === undefined) {
            propertySearch = {};
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<SearchResultSubjectResult>(`${this.basePath}/api/subject`,
            propertySearch,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * updateSubject
     *
     * @param subject subject
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateSubjectUsingPUT(subject: SubjectResult, observe?: 'body', reportProgress?: boolean): Observable<boolean>;
    public updateSubjectUsingPUT(subject: SubjectResult, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<boolean>>;
    public updateSubjectUsingPUT(subject: SubjectResult, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<boolean>>;
    public updateSubjectUsingPUT(subject: SubjectResult, observe: any = 'body', reportProgress: boolean = false): Observable<any> {

        if (subject === null || subject === undefined) {
            throw new Error('Required parameter subject was null or undefined when calling updateSubjectUsingPUT.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<boolean>(`${this.basePath}/api/subject/update`,
            subject,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
